package hbi.core.emp.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "hap_employees")
public class Employees extends BaseDTO {
     @Id
     @GeneratedValue
      private Long employeeId;

     @NotEmpty
      private String name;

     @NotEmpty
      private String sex;

     @NotEmpty
      private String nativePlace;

      private Date bornDate;

      private Long luckyNum;

      private String description;

      private Long programId;

      private Long requestId;

      private String parentId;

    public String getParentId() {
        return parentId;
    }

    public Employees setParentId(String parentId) {
        this.parentId = parentId;
        return this;
    }

    public void setEmployeeId(Long employeeId){
         this.employeeId = employeeId;
     }

     public Long getEmployeeId(){
         return employeeId;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setSex(String sex){
         this.sex = sex;
     }

     public String getSex(){
         return sex;
     }

     public void setNativePlace(String nativePlace){
         this.nativePlace = nativePlace;
     }

     public String getNativePlace(){
         return nativePlace;
     }

     public void setBornDate(Date bornDate){
         this.bornDate = bornDate;
     }

     public Date getBornDate(){
         return bornDate;
     }

     public void setLuckyNum(Long luckyNum){
         this.luckyNum = luckyNum;
     }

     public Long getLuckyNum(){
         return luckyNum;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     }
