package hbi.core.bom.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "bom_chginfo")
public class Chginfo extends BaseDTO {
     @Id
     @GeneratedValue
      private Long chginfoId;

      private String name;

      private String processor;

      private String inworksol;

      private String stocksol;

      private String testsol;

      private String softwaresol;


     public void setChginfoId(Long chginfoId){
         this.chginfoId = chginfoId;
     }

     public Long getChginfoId(){
         return chginfoId;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setProcessor(String processor){
         this.processor = processor;
     }

     public String getProcessor(){
         return processor;
     }

     public void setInworksol(String inworksol){
         this.inworksol = inworksol;
     }

     public String getInworksol(){
         return inworksol;
     }

     public void setStocksol(String stocksol){
         this.stocksol = stocksol;
     }

     public String getStocksol(){
         return stocksol;
     }

     public void setTestsol(String testsol){
         this.testsol = testsol;
     }

     public String getTestsol(){
         return testsol;
     }

     public void setSoftwaresol(String softwaresol){
         this.softwaresol = softwaresol;
     }

     public String getSoftwaresol(){
         return softwaresol;
     }

     }
