package hbi.core.bom.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "bom_delete_part")
public class DeletePart extends BaseDTO {
     @Id
     @GeneratedValue
      private Long deletePartId;

     @NotEmpty
      private String soid;

     @NotEmpty
      private String toid;

     @NotEmpty
      private String oid;

     @NotEmpty
      private String number;

      private String name;

      private String pnumber;

      private String pname;

      private String solution;

      private String description;


     public void setDeletePartId(Long deletePartId){
         this.deletePartId = deletePartId;
     }

     public Long getDeletePartId(){
         return deletePartId;
     }

     public void setSoid(String soid){
         this.soid = soid;
     }

     public String getSoid(){
         return soid;
     }

     public void setToid(String toid){
         this.toid = toid;
     }

     public String getToid(){
         return toid;
     }

     public void setOid(String oid){
         this.oid = oid;
     }

     public String getOid(){
         return oid;
     }

     public void setNumber(String number){
         this.number = number;
     }

     public String getNumber(){
         return number;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setPnumber(String pnumber){
         this.pnumber = pnumber;
     }

     public String getPnumber(){
         return pnumber;
     }

     public void setPname(String pname){
         this.pname = pname;
     }

     public String getPname(){
         return pname;
     }

     public void setSolution(String solution){
         this.solution = solution;
     }

     public String getSolution(){
         return solution;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     }
