package hbi.core.bom.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "bom_effect_object")
public class EffectObject extends BaseDTO {
    @Id
    @GeneratedValue
    private Long objectId;

    private Long chginfoId;

    private String oid;

    private String number;

    private String name;

    private String type;

    private String version;

    private String state;

    private String modifyer;

    private String isauthen;

    private String authenpart;

    private String chgdescription;

    private String inworksol;

    private String stocksol;

    private String testsol;

    private String softwaresol;

    private String isdeletema;

    private String description;


    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getIsauthen() {
        return isauthen;
    }

    public void setIsauthen(String isauthen) {
        this.isauthen = isauthen;
    }

    public String getAuthenpart() {
        return authenpart;
    }

    public void setAuthenpart(String authenpart) {
        this.authenpart = authenpart;
    }

    public void setObjectId(Long objectId){
        this.objectId = objectId;
    }

    public Long getObjectId(){
        return objectId;
    }

    public void setChginfoId(Long chginfoId){
        this.chginfoId = chginfoId;
    }

    public Long getChginfoId(){
        return chginfoId;
    }

    public void setOid(String oid){
        this.oid = oid;
    }

    public String getOid(){
        return oid;
    }

    public void setChgdescription(String chgdescription){
        this.chgdescription = chgdescription;
    }

    public String getChgdescription(){
        return chgdescription;
    }

    public void setInworksol(String inworksol){
        this.inworksol = inworksol;
    }

    public String getInworksol(){
        return inworksol;
    }

    public void setStocksol(String stocksol){
        this.stocksol = stocksol;
    }

    public String getStocksol(){
        return stocksol;
    }

    public void setTestsol(String testsol){
        this.testsol = testsol;
    }

    public String getTestsol(){
        return testsol;
    }

    public void setSoftwaresol(String softwaresol){
        this.softwaresol = softwaresol;
    }

    public String getSoftwaresol(){
        return softwaresol;
    }

    public void setIsdeletema(String isdeletema){
        this.isdeletema = isdeletema;
    }

    public String getIsdeletema(){
        return isdeletema;
    }

    public void setDescription(String description){
        this.description = description;
    }

    public String getDescription(){
        return description;
    }

    public String getModifyer() {
        return modifyer;
    }

    public void setModifyer(String modifyer) {
        this.modifyer = modifyer;
    }
}
