package hbi.core.bom.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "bom_key_part")
public class KeyPart extends BaseDTO {
     @Id
     @GeneratedValue
      private Long keyPartId;

      private String oid;

      private String number;

      private String name;

      private String keyNumber;

      private String keyname;

      private String authenpart;


     public void setKeyPartId(Long keyPartId){
         this.keyPartId = keyPartId;
     }

     public Long getKeyPartId(){
         return keyPartId;
     }

     public void setOid(String oid){
         this.oid = oid;
     }

     public String getOid(){
         return oid;
     }

     public void setNumber(String number){
         this.number = number;
     }

     public String getNumber(){
         return number;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setKeyNumber(String keyNumber){
         this.keyNumber = keyNumber;
     }

     public String getKeyNumber(){
         return keyNumber;
     }

     public void setKeyname(String keyname){
         this.keyname = keyname;
     }

     public String getKeyname(){
         return keyname;
     }

     public void setAuthenpart(String authenpart){
         this.authenpart = authenpart;
     }

     public String getAuthenpart(){
         return authenpart;
     }

     }
