package hbi.core.bom.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "bom_part_basic_att")
public class PartBasicAtt extends BaseDTO {
     @Id
     @GeneratedValue
      private Long basicAttId;

      private String ida2a2;

      private String username;

      private String number;

      private String name;

      private String version;

      private String status;

      private String view;

      private String state;

      private String modifyer;

      private String modtime;

      private String createtime;

      private String container;


     public void setBasicAttId(Long basicAttId){
         this.basicAttId = basicAttId;
     }

     public Long getBasicAttId(){
         return basicAttId;
     }

     public void setIda2a2(String ida2a2){
         this.ida2a2 = ida2a2;
     }

     public String getIda2a2(){
         return ida2a2;
     }

     public void setUsername(String username){
         this.username = username;
     }

     public String getUsername(){
         return username;
     }

     public void setNumber(String number){
         this.number = number;
     }

     public String getNumber(){
         return number;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setVersion(String version){
         this.version = version;
     }

     public String getVersion(){
         return version;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     public void setView(String view){
         this.view = view;
     }

     public String getView(){
         return view;
     }

     public void setState(String state){
         this.state = state;
     }

     public String getState(){
         return state;
     }

     public void setModifyer(String modifyer){
         this.modifyer = modifyer;
     }

     public String getModifyer(){
         return modifyer;
     }

     public void setModtime(String modtime){
         this.modtime = modtime;
     }

     public String getModtime(){
         return modtime;
     }

     public void setCreatetime(String createtime){
         this.createtime = createtime;
     }

     public String getCreatetime(){
         return createtime;
     }

     public void setContainer(String container){
         this.container = container;
     }

     public String getContainer(){
         return container;
     }

     }
