package hbi.core.bom.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "bom_replace_part")
public class ReplacePart extends BaseDTO {
     @Id
     @GeneratedValue
      private Long partId;

      private String linkida2a2;

      private String number;

      private String name;

      private String container;


     public void setPartId(Long partId){
         this.partId = partId;
     }

     public Long getPartId(){
         return partId;
     }

     public void setLinkida2a2(String linkida2a2){
         this.linkida2a2 = linkida2a2;
     }

     public String getLinkida2a2(){
         return linkida2a2;
     }

     public void setNumber(String number){
         this.number = number;
     }

     public String getNumber(){
         return number;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setContainer(String container){
         this.container = container;
     }

     public String getContainer(){
         return container;
     }

     }
