package hbi.core.bom.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "bom_revise_failure")
public class ReviseFailure extends BaseDTO {
     @Id
     @GeneratedValue
      private Long failureId;

      private Long chginfoId;

      private Long reviseId;

      private String oid;

      private String soid;

      private String number;

      private String name;

      private String type;

      private String version;

      private String descripton;


     public void setFailureId(Long failureId){
         this.failureId = failureId;
     }

     public Long getFailureId(){
         return failureId;
     }

     public void setChginfoId(Long chginfoId){
         this.chginfoId = chginfoId;
     }

     public Long getChginfoId(){
         return chginfoId;
     }

     public void setReviseId(Long reviseId){
         this.reviseId = reviseId;
     }

     public Long getReviseId(){
         return reviseId;
     }

     public void setOid(String oid){
         this.oid = oid;
     }

     public String getOid(){
         return oid;
     }

     public void setSoid(String soid){
         this.soid = soid;
     }

     public String getSoid(){
         return soid;
     }

     public void setNumber(String number){
         this.number = number;
     }

     public String getNumber(){
         return number;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setType(String type){
         this.type = type;
     }

     public String getType(){
         return type;
     }

     public void setVersion(String version){
         this.version = version;
     }

     public String getVersion(){
         return version;
     }

     public void setDescripton(String descripton){
         this.descripton = descripton;
     }

     public String getDescripton(){
         return descripton;
     }

     }
