package hbi.core.bom.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "bom_revise")
public class Revise extends BaseDTO {
     @Id
     @GeneratedValue
      private Long reviseId;

      private Long chginfoId;

      private String oid;

      private String soid;

      private String result;

      private String description;


     public void setReviseId(Long reviseId){
         this.reviseId = reviseId;
     }

     public Long getReviseId(){
         return reviseId;
     }

     public void setChginfoId(Long chginfoId){
         this.chginfoId = chginfoId;
     }

     public Long getChginfoId(){
         return chginfoId;
     }

     public void setOid(String oid){
         this.oid = oid;
     }

     public String getOid(){
         return oid;
     }

     public void setSoid(String soid){
         this.soid = soid;
     }

     public String getSoid(){
         return soid;
     }

     public void setResult(String result){
         this.result = result;
     }

     public String getResult(){
         return result;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     }
