package hbi.core.bom.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "bom_wnc_part")
public class WncPart extends BaseDTO {
     @Id
     @GeneratedValue
      private Long wncPartId;

     @NotEmpty
      private String oid;

     @NotEmpty
      private String number;

      private String name;

      private String type;

      private String version;

      private String state;

      private String modifyer;

      private String isauthen;

      private String authenpart;


     public void setWncPartId(Long wncPartId){
         this.wncPartId = wncPartId;
     }

     public Long getWncPartId(){
         return wncPartId;
     }

     public void setOid(String oid){
         this.oid = oid;
     }

     public String getOid(){
         return oid;
     }

     public void setNumber(String number){
         this.number = number;
     }

     public String getNumber(){
         return number;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setType(String type){
         this.type = type;
     }

     public String getType(){
         return type;
     }

     public void setVersion(String version){
         this.version = version;
     }

     public String getVersion(){
         return version;
     }

     public void setState(String state){
         this.state = state;
     }

     public String getState(){
         return state;
     }

     public void setModifyer(String modifyer){
         this.modifyer = modifyer;
     }

     public String getModifyer(){
         return modifyer;
     }

     public void setIsauthen(String isauthen){
         this.isauthen = isauthen;
     }

     public String getIsauthen(){
         return isauthen;
     }

     public void setAuthenpart(String authenpart){
         this.authenpart = authenpart;
     }

     public String getAuthenpart(){
         return authenpart;
     }

     }
